alpahet = {
    'e': {'imageName': 'Eye', 'imageUrl': './assets/images/png/Eye.png', 'points': 10 },
    't': {'imageName': 'Tape', 'imageUrl': './assets/images/png/Tape.png', 'points': 10 },
    'i': {'imageName': 'Insect', 'imageUrl': './assets/images/png/Insect.png', 'points': 15 },
    'a': {'imageName': 'Archery', 'imageUrl': './assets/images/png/Archery.png', 'points': 20 },
    'n': {'imageName': 'Net', 'imageUrl': './assets/images/png/Net.png', 'points': 20 },
    'm': {'imageName': 'Mustache', 'imageUrl': './assets/images/png/Mustache.png', 'points': 20 },
    's': {'imageName': 'Submarine', 'imageUrl': './assets/images/png/Submarine.png', 'points': 40 },
    'u': {'imageName': 'Unicorn', 'imageUrl': './assets/images/png/Unicorn.png', 'points': 40 },
    'r': {'imageName': 'Robot', 'imageUrl': './assets/images/png/Robot.png', 'points': 40 },
    'w': {'imageName': 'Wand', 'imageUrl': './assets/images/png/Wand.png', 'points': 40 },
    'd': {'imageName': 'Dog', 'imageUrl': './assets/images/png/Dog.png', 'points': 40 },
    'k': {'imageName': 'Kite', 'imageUrl': './assets/images/png/Kite.png', 'points': 50 },
    'g': {'imageName': 'Giraffe', 'imageUrl': './assets/images/png/Giraffe.png', 'points': 50 },
    'o': {'imageName': 'Orchestra', 'imageUrl': './assets/images/png/Orchestra.png', 'points': 50 },
    'h': {'imageName': 'Hippo', 'imageUrl': './assets/images/png/Hippo.png', 'points': 50 },
    'v': {'imageName': 'Vacuum', 'imageUrl': './assets/images/png/Vacuum.png', 'points': 60 },
    'f': {'imageName': 'Firetruck', 'imageUrl': './assets/images/png/Firetruck.png', 'points': 60 },
    'l': {'imageName': 'Laboratory', 'imageUrl': './assets/images/png/Laboratory.png', 'points': 60 },
    'p': {'imageName': 'Paddle', 'imageUrl': './assets/images/png/Paddle.png', 'points': 60 },
    'j': {'imageName': 'Jet', 'imageUrl': './assets/images/png/Jet.png', 'points': 70 },
    'b': {'imageName': 'Banjo', 'imageUrl': 'assets/images/png/Banjo.png', 'points': 70 },
    'x': {'imageName': 'X-ray', 'imageUrl': './assets/images/png/X-ray.png', 'points': 80 },
    'c': {'imageName': 'Candy', 'imageUrl': './assets/images/png/Candy.png', 'points': 80 },
    'y': {'imageName': 'Yard', 'imageUrl': './assets/images/png/Yard.png', 'points': 80 },
    'z': {'imageName': 'Zebra', 'imageUrl': './assets/images/png/Zebra.png', 'points': 100 },
    'q': {'imageName': 'Quarterback', 'imageUrl': './assets/images/png/Quarterback.png', 'points': 1000 },
}
