const levels = {
    1: {'itemName': 'balloon', 'itemUrl':'./assets/images/png/mr-lost-stuff/balloon.jpg', 'words': ['e', 't', 'i', 'e', 't', 'i']},
    2: {'itemName': 'book', 'itemUrl':'./assets/images/png/mr-lost-stuff/book.jpg', 'words': ['a', 'e', 'i', 'a', 't', 'n']},
    3: {'itemName': 'coffee', 'itemUrl':'./assets/images/png/mr-lost-stuff/coffee.jpg', 'words': ['i', 'f', 'n', 'e', 'a', 'd']},
    4: {'itemName': 'hat', 'itemUrl':'./assets/images/png/mr-lost-stuff/hat.jpg', 'words': ['f', 'd', 'm', 'i', 's', 't']},
    5: {'itemName': 'key', 'itemUrl':'./assets/images/png/mr-lost-stuff/key.jpg', 'words': ['d', 'a', 'r', 'n', 'f', 's']},
    6: {'itemName': 'pencil', 'itemUrl':'./assets/images/png/mr-lost-stuff/pencil.jpg', 'words': ['m', 'j', 'r', 'e', 'g', 's']},
    7: {'itemName': 'balloon', 'itemUrl':'./assets/images/png/mr-lost-stuff/balloon.jpg', 'words': ['g', 'j', 'r', 's', 'a', 'h']},
    8: {'itemName': 'book', 'itemUrl':'./assets/images/png/mr-lost-stuff/book.jpg', 'words': ['c', 'f', 'e', 'h', 'd', 'v']},
    9: {'itemName': 'coffee', 'itemUrl':'./assets/images/png/mr-lost-stuff/coffee.jpg', 'words': ['c', 'g', 'i', 'v', 'n', 'b']},
    10: {'itemName': 'hat', 'itemUrl':'./assets/images/png/mr-lost-stuff/hat.jpg', 'words': ['c', 's', 'j', 'h', 'b', 'q']},
    11: {'itemName': 'key', 'itemUrl':'./assets/images/png/mr-lost-stuff/key.jpg', 'words': ['b', 'c', 'm', 'q', 'f', 'o']},
    12: {'itemName': 'pencil', 'itemUrl':'./assets/images/png/mr-lost-stuff/pencil.jpg', 'words': ['v', 'p', 'm', 'b', 'o', 'q']},
    13: {'itemName': 'balloon', 'itemUrl':'./assets/images/png/mr-lost-stuff/balloon.jpg', 'words': ['h', 'g', 's', 'd', 'o', 'j']},
    14: {'itemName': 'book', 'itemUrl':'./assets/images/png/mr-lost-stuff/book.jpg', 'words': ['c', 's', 'a', 'c', 'e', 'y']},
    15: {'itemName': 'coffee', 'itemUrl':'./assets/images/png/mr-lost-stuff/coffee.jpg', 'words': ['t', 'n', 'u', 'd', 'r', 'y']},
    16: {'itemName': 'hat', 'itemUrl':'./assets/images/png/mr-lost-stuff/hat.jpg', 'words': ['f', 'b', 'h', 'q', 'g', 'x']},
    17: {'itemName': 'key', 'itemUrl':'./assets/images/png/mr-lost-stuff/key.jpg', 'words': ['s', 'p', 'x', 'u', 'd', 'w']},
    18: {'itemName': 'pencil', 'itemUrl':'./assets/images/png/mr-lost-stuff/pencil.jpg', 'words': ['y', 'q', 'm', 'w', 'b', 'v']},
    19: {'itemName': 'balloon', 'itemUrl':'./assets/images/png/mr-lost-stuff/balloon.jpg', 'words': ['z', 'x', 'i', 'g', 'f', 't']},
    20: {'itemName': 'book', 'itemUrl':'./assets/images/png/mr-lost-stuff/book.jpg', 'words': ['k', 'z', 'p', 'u', 'v', 'x']},
    21: {'itemName': 'coffee', 'itemUrl':'./assets/images/png/mr-lost-stuff/coffee.jpg', 'words': ['k', 'c', 'w', 'z', 'l', 'j']},
    22: {'itemName': 'hat', 'itemUrl':'./assets/images/png/mr-lost-stuff/hat.jpg', 'words': ['k', 'g', 'w', 'h', 'l', 'j']},
    23: {'itemName': 'key', 'itemUrl':'./assets/images/png/mr-lost-stuff/key.jpg', 'words': ['e', 't', 'l', 'k', 'z', 'm']}
}